### ISSUE TITLE
@ACL\HasPermissions  annotation not creating column when driver == config

### ISSUE THREAD

**Issue by DanWithams** [laravel-doctrine/acl#1]
With ALC config settings;

'driver' => 'config'

users.permissions column is not being created when running either;

doctrine:schema:update
doctrine:migrations:diff

**Comment by DanWithams** [comment]
This also extends to \* @HasRoles

**Comment by patrickbrouwers** [comment]
Did you make the User implement the `HasRoles` and `HasPermissions` interfaces?
