### ISSUE TITLE
Mapping is invalid

### ISSUE THREAD

**Issue by jebbdomingo** [laravel-doctrine/acl#10]
When running `$ php artisan doctrine:schema:validate`
It says:
`* The association Services\User\Data\Entities\User\User#roles refers to the inverse side field Services\User\Data\Roles\Role#users which does not exist.`

Though the actual checking of roles is working correctly.

**Comment by patrickbrouwers** [comment]
You need to have a `$users` property in the `Role` entity.

**Comment by vinigarcia87** [comment]
And what's the correct annotation for this property?
