### ISSUE TITLE
Resource specific permissions

### ISSUE THREAD

**Issue by boedy** [laravel-doctrine/acl#12]
I'm currently looking for an ACL package to implement. Would it be possible to use this package for resource specific permissions?

I want to implement some rules like:
- User X is allowed to delete an article in category Y
- User X is allowed to add song to playlist Y

I think it's similar to the connection between user and organisation where an organisation can be seen as category. But It would be hacky to do it like this:

``` php
if($user->belongsToOrganisation(['category:travel']) && $user->hasPermissionTo('delete.article')) {
//some action..
}
```

Maybe something like this would be nice ?:

``` php
if($user->hasPermissionTo('delete.article')->inContextTo('category:travel')->validate()) {
//some action..
}
```

**Comment by patrickbrouwers** [comment]
I think you can be able to implement this syntax sugar yourself, by implementing the `hasPermissionTo` method yourself.

Changing to this syntax wouldn't work out for this package. We need to have `hasPermissionTo` to return a boolean.
