### ISSUE TITLE
Role implements HasPermission

### ISSUE THREAD

**Issue by pmartelletti** [laravel-doctrine/acl#19]
Shouldn't this be optional? So, if I want my role to have permissions, I implement this contract.

Right now, If I implement RoleContract, it will automatically implement HasPermissions (which not necesarily is the expected behaviour).

**Comment by patrickbrouwers** [comment]
The package is called ACL, so access control list which means a list of permissions. If you don't need permissions, this package is of no use to your needs :)

**Comment by pmartelletti** [comment]
indeed I need it - but maybe documentation could be confusion as I may want to have roles per user and not per role?
