### ISSUE TITLE
Annotations fail to subscribe to events when the laravel auth driver is set to doctrine

### ISSUE THREAD

**Issue by LavaToaster** [laravel-doctrine/acl#21]
So, it's been approximately 6+ hours and this person has finally tracked down why `@ACL\HasRole` and `@ACL\HasPermission` is failing to be mapped on our entities, and with that the pivot tables migrations aren't being generated and the properties aren't ArrayCollections.

When `config/auth.php` has `auth.driver` or `auth.providers.users.driver` set to `doctrine` the annotations fail to subscribe to events when the laravel auth driver is set to doctrine.

From my understanding, all managers are singletons in the registry, so once they're booted and resolved that's it. As the auth driver is booted up before the ACL is able to boot, which I presume itself , the subscribers are never resolved. 

I've tried moving the ACL Service Provider to above the ORM's in my `config/app.php` providers, however, I started receiving errors about Gedmo annotations not existing. One solution that I've found to work for me is to move all code in from boot method, minus the config publishes, into the register method, however, I'm not sure if that is the solution here.

You can find an example repo with this setup [here](https://github.com/Lavoaster/laravel-doctrine-auth-with-diff-bug).

Sidenote: This may also affect the `BeberleiExtensionsServiceProvider` as it also injects the `DoctrineManager` class add a callback, but I haven't tested it.

**Comment by patrickbrouwers** [comment]
Thanks for the test repo, makes it easy to reproduce. Will let you know

**Comment by patrickbrouwers** [comment]
Got it working with your repo now. 

Might be good to add the inverse of the HasRoles to the Role entity:

```
/**
     * @ORM\ManyToMany(targetEntity="User", mappedBy="roles")
     * @var ArrayCollection|User[]
     **/
    protected $users;
```

**Comment by LavaToaster** [comment]
Thanks @patrickbrouwers!

Seeing as 50274c4e235792356cdbb208b4d00a9d2d4e3af2 resolves this I'll go ahead and close the issue :smile:
