### ISSUE TITLE
Version 1.0.11 fail to install after composer

### ISSUE THREAD

**Issue by pmartelletti** [laravel-doctrine/acl#22]
When updating to version 1.0.11, I get the following error message:

```
Error Output: PHP Fatal error:  Call to undefined method LaravelDoctrine\ORM\DoctrineManager::onResolve() in /home/pablo/Software/php/jobrole-management/vendor/laravel-doctrine/acl/src/AclServiceProvider.php on line 26
```

**Comment by patrickbrouwers** [comment]
Make sure you update ORM package to 1.0.\* or 1.1.\* as well

**Comment by pmartelletti** [comment]
@patrickbrouwers orm package is on 1.1.0:

```
"laravel-doctrine/orm": "1.1.0",
```

should I get latest?

**Comment by patrickbrouwers** [comment]
You coupled yourself to the specific 1.1.0 version, allowing for no minor updates.

Change it to:

```
"laravel-doctrine/orm": "1.1.*",
```

**Comment by pmartelletti** [comment]
@patrickbrouwers that solved it. I was sticking to 1.1.0 due to previous incompatibility.

Thanks.
