### ISSUE TITLE
Permission Entity

### ISSUE THREAD

**Issue by ghost** [laravel-doctrine/acl#24]
Hi,
I am trying to implemement database permissions.
No error is thrown when the entity inside the config points to default LaravelDoctrine\ACL\Permissions\Permission::class.
But when I replace it with my own App\Permission::class I get this:

ReflectionException in IlluminateRegistry.php line 330:
Class App\Permission does not exist

**Comment by patrickbrouwers** [comment]
Make sure the namespace of your class is correct and autoloaded with PSR-4. 
ReflectionException is a native php exception and would indicate that your class actually does not exist/is not autoloaded.

**Comment by ghost** [comment]
Thank you, I got it to work.
