### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ghost** [laravel-doctrine/acl#29]
After running:
composer require "laravel-doctrine/acl"

and inserting this into config/app.php:
LaravelDoctrine\ACL\AclServiceProvider::class,

I get this:

ErrorException in Manager.php line 8:
Declaration of LaravelDoctrine\ACL\Manager::createDriver($driver, array $settings = Array) should be compatible with LaravelDoctrine\ORM\Configuration\Manager::createDriver($driver, array $settings = Array, $resolve = true)

Laravel 5.3.1

**Comment by steadweb** [comment]
Fixed in `1.0.9` - https://github.com/laravel-doctrine/acl/blob/1.0.9/src/Manager.php

**Comment by patrickbrouwers** [comment]
Laravel 5.3 support is only just released (1.0.14), seems like it tried to install a very old version of acl. Can you retry with the latest version.

**Comment by ghost** [comment]
Works with the latest version, thank you.
