### ISSUE TITLE
Gate helper

### ISSUE THREAD

**Issue by ghost** [laravel-doctrine/acl#31]
From your site:

Using the Gate helper
All permissions are automatically defined inside Laravel's Gate helper.
 Gate::allows('create.posts');
 @can('create.posts');
 $user->can('create.posts');

I cannot get this to work.
So, while this return TRUE:
$user->hasPermissionTo('users.write');
This return FALSE:
\Gate::allows('users.write');

**Comment by ghost** [comment]
Changing the order of providers in config/app.php fixed the issue.

**Comment by kfeng0806** [comment]
@yochanan Can you please explain how did you get fix this?
I did with
```
Gate::allows
@can
$user->can
```
no one get working, maybe any tips?
