### ISSUE TITLE
Relation removed automatically.

### ISSUE THREAD

**Issue by jaydeepesparkinfo** [laravel-doctrine/acl#32]
Hi there I am using doctrine acl for my laravel 5.3 action.

for login I used larvel's default Auth system,
after login to the system it removes relation of role and user.

can anyone help me about this ?

**Comment by gpassarelli** [comment]
Hello there. No updates regarding this issue?

I'm on Laravel 5.5 and still having this problem. And the PR for #25  does not seem to work

**Comment by patrickbrouwers** [comment]
Cannot reproduce this, can anybody provide more information. Preferably a github repo with a reproduceable state.
