### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by websmurf** [laravel-doctrine/acl#43]
### Package version, Laravel version
ACL: v1.0.16
jwt-auth: 1.0.0-rc3
Laravel 5.7

### Problem description
We are seeing quite a slowdown once we upgraded from laravel 5.6 and jwt-auth 1.0.0-rc2 to the latest versions and narrowed it down to a change jwt-auth 1.0.0-rc3 that loads the user provider on each request where this previously wasn't the case. The laravel doctrine user provider will be called and eventually a call to the getAllPermissions function in the PermissionDriver class. This will call the getRepository (https://github.com/laravel-doctrine/acl/blob/1.0/src/Permissions/DoctrinePermissionDriver.php#L91) function which in turn will execute a function to list all tables on the database.
(Doctrine\DBAL\Schema\AbstractSchemaManager::listTableNames)

The query that's being executed is `SHOW FULL TABLES WHERE Table_type = ?`. The performance on our environment for this query is terrible unfortunately. A single call takes about 4-5 seconds to execute. This is most likely due to the amount of databases and tables on our environment (±800 databases with 280 tables each). 

Is there a way to avoid this query from being executed at all? What are your thoughts on this?

**Comment by websmurf** [comment]
Two screenshots from our New Relic account: 
![screenshot-1](https://user-images.githubusercontent.com/4027236/51194949-6194c900-18ec-11e9-8846-8b40d7c82667.png)
![screenshot-2](https://user-images.githubusercontent.com/4027236/51194953-62c5f600-18ec-11e9-986f-f97356f09ed8.png)

**Comment by websmurf** [comment]
Have tried to debug this a bit more into detail, it appears to have been caused by a change in laravel-sentry. On laravel-sentry 0.7.0 all thing run fine, with 0.8.0 thing slow down significantly. 

The only relevant change is this one: getsentry/sentry-laravel#81

**Comment by websmurf** [comment]
Have done a bit more debugging, but this seems to be related to laravel-sentry 0.8.0 and above. 
In 0.7.0 all is fine, since 0.8.0 these problems occur. The only relevant change in 0.8.0 is this one (https://github.com/getsentry/sentry-laravel/pull/81)

Any idea what that could be?

It seems as if in some cases the user request isn't cached at all or something.

**Comment by vv12131415** [comment]
@websmurf can you please explain what does 
> user request isn't cached at all
means. Do you mean laravel doesn't cache or doctrine doesn't cache?

**Comment by websmurf** [comment]
As far as I can see it's not cached at all by either laravel or doctrine. 
It weird, since I don't see this happen on our current production deployment (which is in a docker container). 

Locally, the `getPermissionsWithDotNotation` method is called every single request though. And I haven't been able to explain yet why this doesn't happen on our current production deployment yet. Still debugging that part.

**Comment by vv12131415** [comment]
@websmurf try to see if it's called based on `app.env` or `app.debug`

**Comment by websmurf** [comment]
It doesn't make a difference for some odd reason.

When I remove the laravel-sentry package, the call is executed on every single call as well.
Installing laravel-sentry 0.7.0 removes the call for some reason, upgrading tot 0.8.0 or higher and the call is back again.

I've narrowed it down to the dependency container and it's building the Auth guard with it's dependencies, but I really can't explain what makes the service container behave differently when I install laravel-sentry 0.7.0

**Comment by websmurf** [comment]
No idea what's going on exactly, i've changed the DoctrinePermissionDriver to handle this failure in another way, avoiding the SHOW FULL TABLE query entirely.

You can find this change in #44

**Comment by vv12131415** [comment]
@websmurf can you please provide a test? So I can reproduce it

**Comment by websmurf** [comment]
It's pretty hard to reproduce since this is really something that's going 'wrong' on the mysql side.
You can pretty much reproduce it by placing a sleep of 5 seconds in the MySqlPlatform.php file of Doctrine (https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L360)

```
mysql> SHOW FULL TABLES WHERE Table_type = 'BASE TABLE';
+--------------------------------------------------+------------+
| Tables_in_database_name                     | Table_type |
+--------------------------------------------------+------------+
...redacted...
+--------------------------------------------------+------------+
278 rows in set (6.37 sec)
mysql> 
```

**Comment by garret-gunter** [comment]
Did #44 resolve this?  Or are there still more performance problems?

**Comment by websmurf** [comment]
We haven't experienced issues like the one above since the modification, so closing it.
