### ISSUE TITLE
PHPUnit throws BindingResolutionException error for Gate Contract

### ISSUE THREAD

**Issue by denudge** [laravel-doctrine/acl#47]
When running the ExampleTest in Laravel 5.8, all TestCases shut down with error "Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable."

**Comment by denudge** [comment]
Source: AclServiceProvider.php:28
`$this->app->make(Gate::class)`

**Comment by garret-gunter** [comment]
What is the order of your providers in `config/app.php`?  Are you registering `LaravelDoctrine\ACL\AclServiceProvider` before `Illuminate\Auth\AuthServiceProvider`?

**Comment by eigan** [comment]
@denudge Did you fix this? :)
