### ISSUE TITLE
i'm going to login and than below error show

### ISSUE THREAD

**Issue by rutvikb6044** [laravel-doctrine/acl#53]
Target class [App\Http\Middleware\DisablePreventBack] does not exist.

Illuminate\Container\Container::build
:805
vendor/laravel/framework/src/Illuminate/Container/Container.php:805

     *

     * @throws \Illuminate\Contracts\Container\BindingResolutionException

     */

    public function build($concrete)

    {

        // If the concrete type is actually a Closure, we will just execute it and

        // hand back the results of the functions, which allows functions to be

        // used as resolvers for more fine-tuned resolution of these objects.

        if ($concrete instanceof Closure) {

            return $concrete($this, $this->getLastParameterOverride());

        }

 

        try {

            $reflector = new ReflectionClass($concrete);

        } catch (ReflectionException $e) {

            throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);

        }

 

        // If the type is not instantiable, the developer is attempting to resolve

        // an abstract type such as an Interface or Abstract Class and there is

        // no binding registered for the abstractions so we need to bail out.

        if (! $reflector->isInstantiable()) {

            return $this->notInstantiable($concrete);

        }

 

        $this->buildStack[] = $concrete;

 

        $constructor = $reflector->getConstructor();

 

Any idea how I could debug this issue?

**Comment by eigan** [comment]
Search your codebase for the use of `DisablePreventBack`. Since its a middleware, is it most likely used in your Kernel. 
If its not there, check your cache in `bootstrap/cache/` (`artisan route:clear` `artisan cache:clear` `artisan config:clear`).

**Comment by rutvikb6044** [comment]
it's does't work

**Comment by eigan** [comment]
Why do you think this is related to laravel-doctrine?

**Comment by rutvikb6044** [comment]
http://15.207.50.144/home 
you can check it

**Comment by eigan** [comment]
You should ask the Laravel community. 
I don't think your issue is related to laravel-doctrine. 

You should provide at least the full stacktrace.
