### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by eigan** [laravel-doctrine/acl#56]
There is an optional parameter before required in `MappedEventSubscriber`. Should look into fixing that.

**Comment by aftabnaveed** [comment]
@eigan  any word on this, when do you think this can be merged?

**Comment by eigan** [comment]
@aftabnaveed Open for a PR :+1:

**Comment by PEM-FR** [comment]
It seems like a very trivial fix?
https://github.com/vast-ru/acl/commit/fd719961609bfc8e56ea60d3c376957c1d5ba192

Should we fork the repo, make a branch, then make a pull request?
It somehow feels like a lot of useless steps for such a tiny fix.
If absolutely required, I can do that but I think it'd be faster for you to patch directly, no?
The review time might take longer than the patching

**Comment by eigan** [comment]
@PEM-FR I have asked the author of that commit for permission to merge it into this project now. He have previously contributed, not sure why this commit wasn't opened as a PR.

**Comment by PEM-FR** [comment]
@eigan 
Oh, ok. If he doesn't reply, should we just do the same in this repo?
Also, I am considering contributing to laravel-doctrine at some point :)
I feel that laravel is way too tightly coupled with eloquent, and I would love to see more doctrine related tools

**Comment by eigan** [comment]
> Also, I am considering contributing to laravel-doctrine at some point 

Great to hear!
